# Generated by Django 3.0.7 on 2020-06-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.FloatField(default=0)),
                ('enginesize', models.FloatField(default=0)),
                ('cylinders', models.FloatField(default=0)),
                ('horsepower', models.FloatField(default=0)),
                ('mpgcity', models.FloatField(default=0)),
                ('mpghighway', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('wheelbase', models.FloatField(default=0)),
                ('length', models.FloatField(default=0)),
            ],
        ),
    ]
